
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: test
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      # NodePort can set there, for example: `NodePort: 80`.
  selector:
    app: nginx
    type: frontend
