
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: test
spec:
  clusterIP: 10.43.0.50
  clusterIPs:
   - 10.43.0.50
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
    type: frontend
