
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-rs
  namespace: test
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In # or Equal or NotIn
        values:
          - nginx
          - apache
  template:
    metadata:
      name: rs-template
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-po
          image: nginx:latest
